<?php

/**
 * @file
 * Contains mollo_blog.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\mollo_utils\Utility\ViewFilter;

/**
 * Implements hook_help().
 */
function mollo_blog_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the mollo_blog module.
    case 'help.page.mollo_blog':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Blog Module for Mollo Business') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function mollo_blog_theme() {
  return [
    'mollo_blog' => [
      'render element' => 'children',
    ],
  ];
}
function mollo_blog_form_alter(&$form, &$form_state, $form_id)
{
}

